// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLpdRplBO5S5RQlqvy3Q6-K44P2vEZzPU',
    appId: '1:412146950259:web:293c94e159a978f7f18a06',
    messagingSenderId: '412146950259',
    projectId: 'mothailoan',
    authDomain: 'mothailoan.firebaseapp.com',
    storageBucket: 'mothailoan.firebasestorage.app',
    measurementId: 'G-N2TGE4E8M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKg2f_o1mJWtqU-GJWLAvwMIZ7hq0YKpI',
    appId: '1:412146950259:android:8f1597134c69d014f18a06',
    messagingSenderId: '412146950259',
    projectId: 'mothailoan',
    storageBucket: 'mothailoan.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLpdRplBO5S5RQlqvy3Q6-K44P2vEZzPU',
    appId: '1:412146950259:web:293c94e159a978f7f18a06',
    messagingSenderId: '412146950259',
    projectId: 'mothailoan',
    authDomain: 'mothailoan.firebaseapp.com',
    storageBucket: 'mothailoan.firebasestorage.app',
    measurementId: 'G-N2TGE4E8M8',
  );
}
